go7007 - Add missing dependency on sound subsystem
The dependency on the sound system is missing for go7007 driver, which
resulted in missing symbols like
  drivers/built-in.o: In function `go7007_snd_remove':
  : undefined reference to `snd_card_disconnect'
  drivers/built-in.o: In function `go7007_snd_remove':
  : undefined reference to `snd_card_free_when_closed'
  ...

This patch adds the dependency on CONFIG_SND, and selects CONFIG_SND_PCM
properly.

Signed-off-by: Takashi Iwai <tiwai@suse.de>
Tested-by: Ingo Molnar <mingo@elte.hu>
Cc: Ross Cohen <rcohen@snurgle.org>
Cc: Greg Kroah-Hartman <gregkh@suse.de>