V4L/DVB (8326): sms1xxx: fix missing #include <linux/types.h>
Fix the build error:

smscoreapi.c:689: error: 'uintptr_t' undeclared

Thanks to Peter Schlaf for reporting this.

Cc: Peter Schlaf <peter.schlaf@web.de>

Signed-off-by: Michael Krufky <mkrufky@linuxtv.org>
Signed-off-by: Mauro Carvalho Chehab <mchehab@infradead.org>