[PATCH] let SOUND_AD1889 depend on PCI
Compiling SOUND_AD1889 with PCI=n results in the following compile
error:

sound/built-in.o(.text+0x24f0c): In function `ad1889_remove':
: undefined reference to `pci_release_region'

This patch adds the missing dependency on PCI.

Signed-off-by: Adrian Bunk <bunk@stusta.de>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>