[SPARC]: block/ needed in final image link
With this fix, sparc links vmlinuz again using crosstool.  Without this
fix, the final link fails missing several dozen dozen symbols, beginning
with:

    kernel/built-in.o(.text+0x6fd0): In function `do_exit':
    : undefined reference to `exit_io_context'

(exit_io_context is defined in block/ll_rw_blk.c).

Signed-off-by: Paul Jackson <pj@sgi.com>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: David S. Miller <davem@davemloft.net>