V4L/DVB (8433): Fix macro name at z0194a.h
As reported by Hans Verkuil:

In file included from /home/v4l/master/v4l/dw2102.c:14:
/home/v4l/master/v4l/z0194a.h:93: error: 'STV0229_LOCKOUTPUT_1' undeclared here (not in a function)

This is due to some typos that were fixed on stv0299.

This patch renames it in accord with that fix.

Signed-off-by: Mauro Carvalho Chehab <mchehab@infradead.org>