[ARM] export symbol csum_partial_copy_from_user
I've got the following linking error when building 2.6.21-mm2 on ARM:
	ERROR: "csum_partial_copy_from_user" [net/rxrpc/af-rxrpc.ko] undefined!
Linking fails because "csum_partial_copy_from_user" is not exported to
modules. This patch adds it to the list of exported symbols.

Signed-off-by: Frederik Deweerdt <frederik.deweerdt@gmail.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>