include/video/atmel_lcdc.h must #include <linux/workqueue.h>
This patch fixes the following compile error caused by
commit d22579b837358cbef12ccca5adaf7e93ae09ab7a
(atmel_lcdfb: FIFO underflow management):

<--  snip  -->

...
  CC      arch/avr32/boards/atstk1000/atstk1004.o
In file included from /home/bunk/linux/kernel-2.6/git/linux-2.6/arch/avr32/boards/atstk1000/atstk1004.c:21:
/home/bunk/linux/kernel-2.6/git/linux-2.6/include/video/atmel_lcdc.h:40: error: field 'task' has incomplete type
make[2]: *** [arch/avr32/boards/atstk1000/atstk1004.o] Error 1

<--  snip  -->

Reported-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: Haavard Skinnemoen <haavard.skinnemoen@atmel.com>