[POWERPC] Fix ARCH=ppc builds
The recent signal rework broke ARCH=ppc builds with the following
error:

CC      arch/powerpc/kernel/signal.o
arch/powerpc/kernel/signal.c: In function Âdo_signalÂ:
arch/powerpc/kernel/signal.c:142: error: implicit declaration of
function Âset_dabrÂ
make[1]: *** [arch/powerpc/kernel/signal.o] Error 1

This fixes it by including a function prototype in asm-ppc/system.h.

Acked-by: Kumar Gala <galak@kernel.crashing.org>
Signed-off-by: Josh Boyer <jwboyer@linux.vnet.ibm.com>
Signed-off-by: Paul Mackerras <paulus@samba.org>