V4L/DVB (4804): Fix missing i2c dependency for saa7110
drivers/media/video/saa7110.c:112: undefined reference to `i2c_master_send'
drivers/built-in.o: In function `saa7110_read':
drivers/media/video/saa7110.c:130: undefined reference to `i2c_smbus_read_byte'
drivers/media/video/saa7110.c:130: undefined reference to `i2c_smbus_read_byte'

Signed-off-by: Mauro Carvalho Chehab <mchehab@infradead.org>