ARM: OMAP: Fix missing workqueue include in board-h2.c
ARM: OMAP: Fix missing #include <linux/workqueue.h> in
board-h2.c resulting in

In file included from arch/arm/mach-omap1/board-h2.c:40:
include/asm/arch/irda.h:27: error: field 'gpio_expa' has
incomplete type

Signed-off-by: Dirk Behme <dirk.behme_at_gmail.com>
Signed-off-by: Tony Lindgren <tony@atomide.com>