[GIANFAR]: Fix compile error in latest git
I recognized a compile error in latest git:

/here/workdir/git/drivers/net/gianfar.c: In function `gfar_vlan_rx_kill_vid':
/here/workdir/git/drivers/net/gianfar.c:1135: error: structure has no member named `vgrp'

This error was introduced in commit:

commit 6d04e3b04b6ab569cabeb5ca28ad1be11777e895
 ...
      [VLAN]: Avoid a 4-order allocation.


Signed-off-by: Jan Altenberg <jan@linutronix.de>
Signed-off-by: David S. Miller <davem@davemloft.net>