[PATCH] mtd, nettel: fix build error and implicit declaration
I just hit the following error and warning :
  drivers/mtd/maps/nettel.c: In function `nettel_init':
  drivers/mtd/maps/nettel.c:418: error: `ROOT_DEV' undeclared (first use in this function)
  drivers/mtd/maps/nettel.c:418: error: (Each undeclared identifier is reported only once
  drivers/mtd/maps/nettel.c:418: error: for each function it appears in.)
  drivers/mtd/maps/nettel.c:418: warning: implicit declaration of function `MKDEV'
  make[3]: *** [drivers/mtd/maps/nettel.o] Error 1
  make[2]: *** [drivers/mtd/maps] Error 2
  make[1]: *** [drivers/mtd] Error 2
The patch fixes the missing ROOT_DEV declaration by including linux/root_dev.h
and fixes the implicit declaration of MKDEV by including linux/kdev_t.h .

Signed-off-by: Jesper Juhl <jesper.juhl@gmail.com>
Signed-off-by: David Woodhouse <dwmw2@infradead.org>