[ARM] w90x900: fix build errors and warnings
Fix:
arch/arm/mach-w90x900/mach-w90p910evb.c:65: error: 'W90X900_PA_UART' undeclared here (not in a function)

and silence warnings caused by inappropriate inclusion of mach/system.h.

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>