[ARM] Export dma_sync_sg_for_device()
Noticed by Martin Michlmayr, this missing export prevents IEEE1394
from building with:

ERROR: "dma_sync_sg_for_device" [drivers/ieee1394/ieee1394.ko] undefined!

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>