bzip2/lzma: make flush_buffer() unconditional
Impact: build fix

flush_buffer() is used unconditionally:

  init/initramfs.c:456: error: 'flush_buffer' undeclared (first use in this function)
  init/initramfs.c:456: error: (Each undeclared identifier is reported only once
  init/initramfs.c:456: error: for each function it appears in.)

So remove the decompressor #ifdefs from around it.

Signed-off-by: Ingo Molnar <mingo@elte.hu>