kmemtrace, befs: fix slab.h dependency problem
Impact: cleanup

fs/befs/debug.c depends on slab.h without including it. Upcoming
changes for kmemtrace would break the build:

    CC      fs/befs/debug.o
  fs/befs/debug.c: In function ‘befs_error’:
  fs/befs/debug.c:31: error: implicit declaration of function ‘kmalloc’
  fs/befs/debug.c:31: warning: initialization makes pointer from integer without a cast
  fs/befs/debug.c:42: error: implicit declaration of function ‘kfree’
  fs/befs/debug.c: In function ‘befs_warning’:
  fs/befs/debug.c:49: warning: initialization makes pointer from integer without a cast
  fs/befs/debug.c: In function ‘befs_debug’:
  fs/befs/debug.c:73: warning: assignment makes pointer from integer without a cast
  make[1]: *** [fs/befs/debug.o] Error 1
  make: *** [fs/befs/] Error 2

So add the dependency explicitly.

Signed-off-by: Pekka Enberg <penberg@cs.helsinki.fi>
Cc: Eduard - Gabriel Munteanu <eduard.munteanu@linux360.ro>
LKML-Reference: <1237884230.25315.33.camel@penberg-laptop>
Signed-off-by: Ingo Molnar <mingo@elte.hu>