Fix c67x00-ll-hpi compilation failure (bug #10627)
This patch fixes bug #10627 which caused the compilation error below.

  CC [M]  drivers/usb/c67x00/c67x00-ll-hpi.o
  drivers/usb/c67x00/c67x00-ll-hpi.c: In function `ll_recv_msg':
  drivers/usb/c67x00/c67x00-ll-hpi.c:243: erreur: `HZ' undeclared (first use in this function)
  drivers/usb/c67x00/c67x00-ll-hpi.c:243: erreur: (Each undeclared identifier is reported only once
  drivers/usb/c67x00/c67x00-ll-hpi.c:243: erreur: for each function it appears in.)

Signed-off-by: Fernando Luis Vazquez Cao <fernando@oss.ntt.co.jp>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>