Staging: vt6655: uses pci functions, should depend on PCI
This driver uses lots of pci_*() calls, so it should depend on PCI.

drivers/staging/vt6655/device_main.c:3942: error: implicit declaration of function 'pci_dev_driver'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>