net: niu uses crc32, so select CRC32
From: Randy Dunlap <randy.dunlap@oracle.com>

niu drivers uses crc32 functions, so it needs to select CRC32.

niu.c:(.text+0x18a7f8): undefined reference to `crc32_le'

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: David S. Miller <davem@davemloft.net>