[PATCH] CISS: require same SCSI module support
Building CCISS SCSI tape support in-kernel when SCSI=m causes build errors,
so require SCSI support to be =y or same as CCISS SCSI tape support.

  drivers/built-in.o: In function `cciss_remove_one':
  cciss.c:(.text+0x79d4c): undefined reference to `scsi_remove_host'
  cciss.c:(.text+0x79d55): undefined reference to `scsi_host_put'
  drivers/built-in.o: In function `cciss_update_non_disk_devices':
  cciss.c:(.text+0x7bb54): undefined reference to `scsi_device_type'
  cciss.c:(.text+0x7bcc8): undefined reference to `scsi_device_type'
  cciss.c:(.text+0x7be81): undefined reference to `scsi_device_type'
  cciss.c:(.text+0x7bf81): undefined reference to `scsi_device_type'
  drivers/built-in.o: In function `cciss_proc_write':
  cciss.c:(.text+0x7c175): undefined reference to `scsi_host_alloc'
  cciss.c:(.text+0x7c1ed): undefined reference to `scsi_add_host'
  cciss.c:(.text+0x7c1f9): undefined reference to `scsi_scan_host'
  cciss.c:(.text+0x7c206): undefined reference to `scsi_host_put'
  make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Acked-by: Mike Miller <mike.miller@hp.com>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>