Staging: line6: fix build error, select SND_RAWMIDI
line6 needs to select SND_RAWMIDI, like many other drivers do.

ERROR: "snd_rawmidi_set_ops" [drivers/staging/line6/line6usb.ko] undefined!
ERROR: "snd_rawmidi_new" [drivers/staging/line6/line6usb.ko] undefined!
ERROR: "snd_rawmidi_transmit_peek" [drivers/staging/line6/line6usb.ko] undefined!
ERROR: "snd_rawmidi_transmit_ack" [drivers/staging/line6/line6usb.ko] undefined!
ERROR: "snd_rawmidi_receive" [drivers/staging/line6/line6usb.ko] undefined!

Signed-off-by: Randy Dunlap <randy.dunlap@oracle.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@suse.de>