b43: fix build with CONFIG_SSB_PCIHOST=n
m68k allmodconfig gives

drivers/net/wireless/b43/main.c:251: error: implicit declaration of function 'mmiowb'

because CONFIG_B43=m, CONFIG_SSB_PCIHOST=n.

Might be Kconfig bustage, but this works...

Cc: Michael Buesch <mb@bu3sch.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: John W. Linville <linville@tuxdriver.com>