ALSA: opti-miro: Fix missing semicolon
To fix a build error
  sound/isa/opti9xx/miro.c:1281: error: expected ';' before '}' token

Signed-off-by: Takashi Iwai <tiwai@suse.de>