[ARM] EBSA110: fix build errors caused by missing "const"
arch/arm/mach-ebsa110/io.c:106: error: conflicting types for 'readsw'
arch/arm/mach-ebsa110/io.c:116: error: conflicting types for 'readsl'
arch/arm/mach-ebsa110/io.c:161: error: conflicting types for 'writesw'
arch/arm/mach-ebsa110/io.c:171: error: conflicting types for 'writesl'

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>