FRV: Fix compile breakage
This patch fixes the follwing build error caused by
commit 7ca43e7564679604d86e9ed834e7bbcffd8a4a3f
(mm: use debug_kmap_atomic):

  ...
    AS      arch/frv/mm/tlb-miss.o
  In file included from
  arch/frv/mm/tlb-miss.S:13:
  ...
  Assembler messages:
  include/asm-generic/ioctl.h:73:
  Error: unrecognized instruction `extern unsigned int __invalid_size_argument_for_IO...'
  ...

Signed-off-by: Adrian Bunk <bunk@kernel.org>
Signed-off-by: David Howells <dhowells@redhat.com>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>