[PATCH] winbond IDE depends on IDEDMA
winbond ide depends on idedma.
Move the option into the IDEDMA section.

  drivers/built-in.o: In function `.sl82c105_ide_dma_timeout':
  sl82c105.c:(.text+0x624d0): undefined reference to `.__ide_dma_timeout'
  drivers/built-in.o: In function `.sl82c105_ide_dma_off_quietly':
  sl82c105.c:(.text+0x6274c): undefined reference to `.__ide_dma_off_quietly'
  drivers/built-in.o: In function `.sl82c105_ide_dma_on':
  sl82c105.c:(.text+0x6284c): undefined reference to `.__ide_dma_on'
  drivers/built-in.o: In function `.sl82c105_check_drive':
  sl82c105.c:(.text+0x628ec): undefined reference to `.__ide_dma_bad_drive'
  sl82c105.c:(.text+0x62934): undefined reference to `.__ide_dma_good_drive'
  drivers/built-in.o: In function `.sl82c105_ide_dma_start':
  sl82c105.c:(.text+0x62c24): undefined reference to `.ide_dma_start'
  make[1]: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Olaf Hering <olaf@aepfle.de>
Acked-by: "Bartlomiej Zolnierkiewicz" <bzolnier@gmail.com>
Cc: Alan Cox <alan@lxorguk.ukuu.org.uk>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>