[PATCH] Add missing select's to DVB_BUDGET_AV
This fixes the following compile error:

	...
	  LD      .tmp_vmlinux1
	drivers/built-in.o: In function `frontend_init':
	budget-av.c:(.text+0xb9448): undefined reference to `tda10046_attach'
	budget-av.c:(.text+0xb9518): undefined reference to `tda10021_attach'
	drivers/built-in.o: In function `philips_tu1216_request_firmware':
	budget-av.c:(.text+0xb937b): undefined reference to `request_firmware'
	make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Adrian Bunk <bunk@stusta.de>
Acked-by: Johannes Stezenbach <js@linuxtv.org>
Acked-by: Michael Krufky <mkrufky@linuxtv.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>