[ARM] Fix build error caused by move of apm
  CC      arch/arm/common/sharpsl_pm.o
arch/arm/common/sharpsl_pm.c:30:31: error: asm/apm-emulation.h: No such file or directory
...

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>