sh: Add missing dma_sync_single_range_for_*().
The b44 build uses these, caught by allmodconfig:

drivers/net/b44.c: In function `b44_sync_dma_desc_for_cpu':
drivers/net/b44.c:159: error: implicit declaration of function `dma_sync_single_range_for_cpu'

Follow the sparc64 change and stub them in.

Reported-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>