oprofile: select RING_BUFFER
Impact: build fix

OProfile now depends on the ring buffer infrastructure:

 arch/x86/oprofile/built-in.o: In function `oprofile_add_ibs_sample':
 : undefined reference to `ring_buffer_unlock_commit'

Select TRACING and RING_BUFFER when oprofile is enabled.

Signed-off-by: Ingo Molnar <mingo@elte.hu>