V4L/DVB (13039): dib0700: not building CONFIG_DVB_TUNER_DIB0070 breaks compilation
As reported by Ingo Molnar:
 Here's another new build breakage that triggers in -tip testing:

 drivers/built-in.o:(.data+0xb1f40): undefined reference to `dib0070_ctrl_agc_filter'
 drivers/built-in.o:(.data+0xb1f80): undefined reference to `dib0070_ctrl_agc_filter'

triggers due to:

CONFIG_DVB_USB_DIB0700=y
CONFIG_DVB_TUNER_DIB0070 is not set

While working on a better approach, for now, let's just select tuner
dib0070 anytime we compile dib0700.

Cc: Patrick Boettcher <pboettcher@kernellabs.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>