ACPI: prevent build failure when CONFIG_X86_NUMAQ=y
...by disabling CONFIG_ACPI when CONFIG_X86_NUMAQ=y

otherwise arch/i386/pci/Makefile forgets
that it needs to build acpi.o

drivers/built-in.o: In function `acpi_pci_root_add':
pci_root.c:(.text+0x45ec4): undefined reference to `pci_acpi_scan_root'

Signed-off-by: Len Brown <len.brown@intel.com>