[PATCH] ppc64: hide CONFIG_ADB
This bites me all day when I use our default config for ppc64.  We use a
patch to fix the compile errors and provide the CONFIG_MAC_EMUMOUSEBTN
functionality (which is behind CONFIG_INPUT_ADBHID).  But Benh doesnt like
it.

http://ozlabs.org/pipermail/linuxppc64-dev/2005-March/003423.html

Just hide all the ADB parts from via-pmu on ppc64 instead.

drivers/macintosh/adbhid.c: In function `adbhid_init':
drivers/macintosh/adbhid.c:1199: error: `_MACH_chrp' undeclared (first use in this function)
drivers/macintosh/adbhid.c:1199: error: (Each undeclared identifier is reported only once
drivers/macintosh/adbhid.c:1199: error: for each function it appears in.)

Cc: Benjamin Herrenschmidt <benh@kernel.crashing.org>
Cc: Paul Mackerras <paulus@samba.org>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>