m32r: fix build due to notify_cpu_starting() change
fix:

arch/m32r/kernel/smpboot.c:501: err
or: implicit declaration of function 'notify_cpu_starting'
make[2]: *** [arch/m32r/kernel/smpboot.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Signed-off-by: Ingo Molnar <mingo@elte.hu>