[ARM] 4530/1: MXC: fix elf_hwcap compile breakage as in iop13xx
MXC needs the same change as IOP.  See [ARM] 4494/1
or commit 7dea1b20066cd30fb54da7e686b16b5e38b46b2d

An undefined reference to elf_hwcap prevents linkage, due
to changes made by f884b1cf578e079f01682514ae1ae64c74586602
and d1cbbd6b413510c6512f4f80ffd48db1a8dd554a

Removing processor.h removes the extern definition of
elf_hwcap, which fixes the link issue, but forgets cpu_relax().
So, instead, we'll call barrier() directly.

Cc: Lennert Buytenhek <kernel@wantstofly.org>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Ross Wille <wille@freescale.com>
Signed-off-by: Quinn Jensen <quinn.jensen@freescale.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>